config/routes.rb
Website::Application.routes.draw do
  resources :categories

  root :to => "projects#index"

  devise_for :users
  
  resources :users, :only => [:index, :show, :edit, :update, :destroy]
  
  resources :posts, :except => [:index, :show]

  resources :topics, :except => :index

  resources :forums

  resources :projects

end

app/models/topic.rb
# Copyright © 2013 BluePanel.org
#
# This file is part of BluePanel-Website.
# 
#     BluePanel-Website is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     BluePanel-Website is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with BluePanel-Website.  If not, see <http://www.gnu.org/licenses/>.
# 
# Diese Datei ist Teil von BluePanel-Website.
# 
#     BluePanel-Website ist Freie Software: Sie können es unter den Bedingungen
#     der GNU General Public License, wie von der Free Software Foundation,
#     Version 3 der Lizenz oder (nach Ihrer Option) jeder späteren
#     veröffentlichten Version, weiterverbreiten und/oder modifizieren.
# 
#     BluePanel-Website wird in der Hoffnung, dass es nützlich sein wird, aber
#     OHNE JEDE GEWÄHELEISTUNG, bereitgestellt; sogar ohne die implizite
#     Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
#     Siehe die GNU General Public License für weitere Details.
# 
#     Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
#     Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>. 

class Topic < ActiveRecord::Base
  belongs_to :user
  belongs_to :forum
  
  has_many :posts, :dependent => :destroy
  attr_accessible :last_post_at, :last_poster_id, :name, :forum_id, :user_id
end

app/controllers/topics_controller.rb
# Copyright © 2013 BluePanel.org
#
# This file is part of BluePanel-Website.
# 
#     BluePanel-Website is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     BluePanel-Website is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with BluePanel-Website.  If not, see <http://www.gnu.org/licenses/>.
# 
# Diese Datei ist Teil von BluePanel-Website.
# 
#     BluePanel-Website ist Freie Software: Sie können es unter den Bedingungen
#     der GNU General Public License, wie von der Free Software Foundation,
#     Version 3 der Lizenz oder (nach Ihrer Option) jeder späteren
#     veröffentlichten Version, weiterverbreiten und/oder modifizieren.
# 
#     BluePanel-Website wird in der Hoffnung, dass es nützlich sein wird, aber
#     OHNE JEDE GEWÄHELEISTUNG, bereitgestellt; sogar ohne die implizite
#     Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
#     Siehe die GNU General Public License für weitere Details.
# 
#     Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
#     Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>. 

class TopicsController < ApplicationController
  load_and_authorize_resource
  
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(:name => params[:topic][:name],
                       :last_poster_id => current_user.id,
                       :last_post_at => Time.now,
                       :forum_id => params[:topic][:forum_id],
                       :user_id => current_user.id)

    respond_to do |format|
      if @topic.save
        @post = Post.new(:content => params[:post][:content],
                         :topic_id => @topic.id,
                         :user_id => current_user.id)
        if @post.save
          format.html { redirect_to "/forums/#{@topic.forum_id}", notice: 'Topic was successfully created.' }
          format.json { render json: @topic, status: :created, location: @topic }
        else
          format.html { render action: "new" }
          format.json { render json: @topic.errors, status: :unprocessable_entity }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        @post = @topic.posts.first
        if @post.update_attributes(params[:post])
          format.html { redirect_to "/forums/#{@topic.forum_id}", notice: 'Topic was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @topic.errors, status: :unprocessable_entity }
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to "/forums/#{@topic.forum_id}" }
      format.json { head :no_content }
    end
  end
end

app/helpers/topics_helper.rb
# Copyright © 2013 BluePanel.org
#
# This file is part of BluePanel-Website.
# 
#     BluePanel-Website is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     BluePanel-Website is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with BluePanel-Website.  If not, see <http://www.gnu.org/licenses/>.
# 
# Diese Datei ist Teil von BluePanel-Website.
# 
#     BluePanel-Website ist Freie Software: Sie können es unter den Bedingungen
#     der GNU General Public License, wie von der Free Software Foundation,
#     Version 3 der Lizenz oder (nach Ihrer Option) jeder späteren
#     veröffentlichten Version, weiterverbreiten und/oder modifizieren.
# 
#     BluePanel-Website wird in der Hoffnung, dass es nützlich sein wird, aber
#     OHNE JEDE GEWÄHELEISTUNG, bereitgestellt; sogar ohne die implizite
#     Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
#     Siehe die GNU General Public License für weitere Details.
# 
#     Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
#     Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>. 

module TopicsHelper
end

app/views/topics/_form.html.erb
<!--

Copyright © 2013 BluePanel.org

This file is part of BluePanel-Website.

    BluePanel-Website is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BluePanel-Website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BluePanel-Website.  If not, see <http://www.gnu.org/licenses/>.

Diese Datei ist Teil von BluePanel-Website.

    BluePanel-Website ist Freie Software: Sie können es unter den Bedingungen
    der GNU General Public License, wie von der Free Software Foundation,
    Version 3 der Lizenz oder (nach Ihrer Option) jeder späteren
    veröffentlichten Version, weiterverbreiten und/oder modifizieren.

    BluePanel-Website wird in der Hoffnung, dass es nützlich sein wird, aber
    OHNE JEDE GEWÄHELEISTUNG, bereitgestellt; sogar ohne die implizite
    Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
    Siehe die GNU General Public License für weitere Details.

    Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
    Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>. 
    
-->

<%= form_for @topic, :html => { :class => 'form-horizontal' } do |f| %>
  <% if params[:forum] %><input type="hidden" id="topic_forum_id" name="topic[forum_id]" value="<%= params[:forum] %>" /><% end %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <textarea name="post[content]" class="text_area"><%= @topic.posts.first.content unless @topic.posts.first.nil? %></textarea>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <% if @topic.id.nil? %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  "/forums/#{params[:forum]}", :class => 'btn' %>
    <% else %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  topic_path(@topic), :class => 'btn' %>
    <% end %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<!--

Copyright © 2013 BluePanel.org

This file is part of BluePanel-Website.

    BluePanel-Website is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BluePanel-Website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BluePanel-Website.  If not, see <http://www.gnu.org/licenses/>.

Diese Datei ist Teil von BluePanel-Website.

    BluePanel-Website ist Freie Software: Sie können es unter den Bedingungen
    der GNU General Public License, wie von der Free Software Foundation,
    Version 3 der Lizenz oder (nach Ihrer Option) jeder späteren
    veröffentlichten Version, weiterverbreiten und/oder modifizieren.

    BluePanel-Website wird in der Hoffnung, dass es nützlich sein wird, aber
    OHNE JEDE GEWÄHELEISTUNG, bereitgestellt; sogar ohne die implizite
    Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
    Siehe die GNU General Public License für weitere Details.

    Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
    Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>. 
    
-->

<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/topics/index.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:last_poster_id) %></th>
      <th><%= model_class.human_attribute_name(:last_post_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.id, topic_path(topic) %></td>
        <td><%= topic.name %></td>
        <td><%= topic.last_poster_id %></td>
        <td><%= topic.last_post_at %></td>
        <td><%=l topic.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_topic_path(topic), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      topic_path(topic),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_topic_path,
            :class => 'btn btn-primary' %>

app/views/topics/new.html.erb
<!--

Copyright © 2013 BluePanel.org

This file is part of BluePanel-Website.

    BluePanel-Website is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BluePanel-Website is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BluePanel-Website.  If not, see <http://www.gnu.org/licenses/>.

Diese Datei ist Teil von BluePanel-Website.

    BluePanel-Website ist Freie Software: Sie können es unter den Bedingungen
    der GNU General Public License, wie von der Free Software Foundation,
    Version 3 der Lizenz oder (nach Ihrer Option) jeder späteren
    veröffentlichten Version, weiterverbreiten und/oder modifizieren.

    BluePanel-Website wird in der Hoffnung, dass es nützlich sein wird, aber
    OHNE JEDE GEWÄHELEISTUNG, bereitgestellt; sogar ohne die implizite
    Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
    Siehe die GNU General Public License für weitere Details.

    Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
    Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>. 
    
-->

<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/topics/show.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => @topic.name %></h1>
</div>

<% for post in @topic.posts %>  
  <article class="post"> <!-- space for Post ID-->
      
      <div class="post-top">
        <div class="user-name">
          <%= link_to post.user.name, post.user %>
        </div>
        <div class="post-date">
          created on: <%= post.created_at %>
        </div>
      </div>  
      <div class="post-body">
        <div class="left">
          <div class="user-info">
            <%= post.user.title %>
            <%= image_tag(post.user.logo.url(:medium)) %>
            <%= mail_to(post.user.email, 'E-Mail') if user? %>
            <!-- Avatar/ Member Group/ .... -->  
          </div>
        </div>
        <div class="center">
          <div class="post-msg">
    			 <%= post.content.bbcode_to_html.html_safe %>
          </div>
          <div class="sig-line">
          </div>
          <div class="user-sig">
            Signature               
          </div>
        </div>
      </div>
      <% if moderator_or_owner?(post.user.id) %>
      <div class="right">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      "#{edit_post_path(post)}?topic=#{@topic.id}", :class => 'btn btn-mini' unless post == @topic.posts.first %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' unless post == @topic.posts.first %>
      </div>
      <% end %>
  </article>

<% end %>

<% if user? %>
  <p class="reply">
    <%= link_to "Reply", 
                "#{new_post_path}?topic=#{@topic.id}",
                :class =>'btn btn-primary' %>
  </p>
<% end %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              "/forums/#{@topic.forum_id}", :class => 'btn' %>
  <% if moderator_or_owner?(@topic.user.id) %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_topic_path(@topic), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                topic_path(@topic),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  <% end %>
</div>